"""Added status to collection_link

Revision ID: 3400cb002845
Revises: 0be694d02161
Create Date: 2026-01-16 18:35:14.357912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3400cb002845'
down_revision: Union[str, None] = '0be694d02161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_links', sa.Column('activity_status', sa.Enum('ACTIVE', 'BLOCKED', 'ARCHIVED', name='status'), nullable=True))
    # ### end Alembic commands ###
    op.execute(
        "UPDATE collection_links SET activity_status='ACTIVE'"
    )

    op.alter_column('collection_links', 'activity_status', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_links', 'activity_status')
    # ### end Alembic commands ###
