"""Updated parsing tables and added proxy table

Revision ID: eea09c9aea81
Revises: 3400cb002845
Create Date: 2026-01-20 16:25:15.154116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eea09c9aea81'
down_revision: Union[str, None] = '3400cb002845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxies',
    sa.Column('url', sa.String(length=1500), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'TEMP_BLOCKED', 'DEAD', 'UNKNOWN', 'SUSPENDED', name='proxystatus'), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_proxies_id'), 'proxies', ['id'], unique=False)
    op.create_table('parsing_jobs',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELED', name='jobstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('links_total', sa.Integer(), nullable=True),
    sa.Column('links_processed', sa.Integer(), nullable=True),
    sa.Column('vacancies_found', sa.Integer(), nullable=True),
    sa.Column('errors_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsing_jobs_id'), 'parsing_jobs', ['id'], unique=False)
    op.create_table('parsing_tasks',
    sa.Column('parsing_job_id', sa.UUID(), nullable=False),
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'DONE', 'FAILED', 'CANCELED', name='jobtaskstatus'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['link_id'], ['links.id'], ),
    sa.ForeignKeyConstraint(['parsing_job_id'], ['parsing_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsing_tasks_id'), 'parsing_tasks', ['id'], unique=False)
    op.drop_index('ix_parsing_runs_id', table_name='parsing_runs')
    op.drop_table('parsing_runs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parsing_runs',
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'BLOCKED', 'ARCHIVED', name='status'), autoincrement=False, nullable=False),
    sa.Column('links_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('links_processed', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vacancies_found', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('errors_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='parsing_runs_account_id_fkey'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], name='parsing_runs_collection_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='parsing_runs_pkey')
    )
    op.create_index('ix_parsing_runs_id', 'parsing_runs', ['id'], unique=False)
    op.drop_index(op.f('ix_parsing_tasks_id'), table_name='parsing_tasks')
    op.drop_table('parsing_tasks')
    op.drop_index(op.f('ix_parsing_jobs_id'), table_name='parsing_jobs')
    op.drop_table('parsing_jobs')
    op.drop_index(op.f('ix_proxies_id'), table_name='proxies')
    op.drop_table('proxies')
    # ### end Alembic commands ###
