"""Initial migration

Revision ID: f38d775050b6
Revises: 
Create Date: 2025-03-09 14:50:11.935779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f38d775050b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('account_status', sa.Enum('ACTIVE', 'BLOCKED', 'ARCHIVED', name='accountstatus'), nullable=True),
    sa.Column('account_type', sa.Enum('ADMIN', 'SIMPLE', name='accounttype'), nullable=True),
    sa.Column('last_login', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_active', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_table('link_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('activity_status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='activitystatus'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_link_lists_id'), 'link_lists', ['id'], unique=False)
    op.create_table('subscribes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.Enum('MONTHLY', 'YEARLY', name='targettype'), nullable=True),
    sa.Column('activity_status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='activitystatus'), nullable=True),
    sa.Column('end_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_activity', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscribes_id'), 'subscribes', ['id'], unique=False)
    op.create_table('filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_list_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('skills', sa.String(length=255), nullable=True),
    sa.Column('match_of_skills', sa.Boolean(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('salary_range_min', sa.Integer(), nullable=True),
    sa.Column('salary_range_max', sa.Integer(), nullable=True),
    sa.Column('employment_type', sa.String(length=255), nullable=True),
    sa.Column('experience_level', sa.String(length=255), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('active_status', sa.String(length=255), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['link_list_id'], ['link_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filters_id'), 'filters', ['id'], unique=False)
    op.create_index(op.f('ix_filters_link_list_id'), 'filters', ['link_list_id'], unique=False)
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_list_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1500), nullable=False),
    sa.Column('activity_status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='activitystatus'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['link_list_id'], ['link_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_id'), 'links', ['id'], unique=False)
    op.create_index(op.f('ix_links_url'), 'links', ['url'], unique=False)
    op.create_table('parsing_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('link_list_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('jobs_found', sa.Integer(), nullable=True),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['link_list_id'], ['link_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parsing_logs_id'), 'parsing_logs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parsing_logs_id'), table_name='parsing_logs')
    op.drop_table('parsing_logs')
    op.drop_index(op.f('ix_links_url'), table_name='links')
    op.drop_index(op.f('ix_links_id'), table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_filters_link_list_id'), table_name='filters')
    op.drop_index(op.f('ix_filters_id'), table_name='filters')
    op.drop_table('filters')
    op.drop_index(op.f('ix_subscribes_id'), table_name='subscribes')
    op.drop_table('subscribes')
    op.drop_index(op.f('ix_link_lists_id'), table_name='link_lists')
    op.drop_table('link_lists')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
